[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cnctd_studio_program = "CSPd6eauKNBXfrQnKmqrHKEjt6xtW7mgzmfV2XPfiy5i"

[programs.devnet]
cnctd_studio_program = "CSPd6eauKNBXfrQnKmqrHKEjt6xtW7mgzmfV2XPfiy5i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
